linux-x86_64-gcc_task:
  container:
    image: ubuntu:latest

  setup_script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential git cmake libsdl2-dev

  matrix:
    - build_script:
        - mkdir build && cd build
        - cmake .. -G "Unix Makefiles" -DBUILD_SDL2="ON" -DCMAKE_BUILD_TYPE="Release"
        - make -j$(nproc --all)

macOS-x86_64-apple_task:
  macos_instance:
    image: big-sur-base

  setup_script:
    - brew install git cmake pkg-config sdl2

  matrix:
    - build_script:
        - mkdir build && cd build
        - cmake .. -G "Unix Makefiles" -DBUILD_SDL2="ON" -DCMAKE_BUILD_TYPE="Release"
        - make -j$(sysctl -n hw.ncpu)
  