version: 2.1

workflows:
  version: 2.1
  build:
    jobs:
      - ubuntu_gcc

jobs:
  ubuntu_gcc:
    docker:
      - image: "ubuntu:focal"
    environment:
      TZ: "America/Chicago"
    steps:
      - run:
          name: Installing sudo
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing dependencies
          command: 'sudo apt-get update && sudo apt-get upgrade && sudo DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential git cmake libsdl2-dev'
      - checkout
      - run:
          name: Setting up build directory
          command: 'mkdir build && cd build'
      - run:
          name: Configuring build
          command: 'cmake .. -G "Unix Makefiles" -DBUILD_SDL2="ON" -DBUILD_EXAMPLES="ON" -DCMAKE_BUILD_TYPE="Release"'
      - run:
          name: Compiling build
          command: 'make -j$(nproc --all)'
        