trigger:
- main

pool:
  vmImage: macOS-10.14

steps:
- script: brew install sdl2
  displayName: 'Install dependencies'

- script: mkdir $(Pipeline.Workspace)/build
  displayName: 'Create build environment'

- script: cmake $(Build.SourcesDirectory) -DCMAKE_BUILD_TYPE="Release" -DBULD_SDL2="ON"
  displayName: 'Configure'
  workingDirectory: $(Pipeline.Workspace)/build
  
- script: make -j$(sysctl -n hw.logicalcpu)
  displayName: 'Make'
  workingDirectory: $(Pipeline.Workspace)/build